service: default
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "10m" 

handlers:
- url: /.*
  script: server.main.server
  secure: always
  login: required

librairies:
- name: ssl
  version: latest
- name: pycrypto
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?\..*$
- ^node_modules$
- ^env$
- ^\.idea$
- ^\.git$
- ^scripts$
- ^launch\.sh$
- ^secret\.pem$
- ^tasks$
- ^tools$
- ^(.*/)?.*\.py[co]$
- .idea/
- .git/
- .angular-cli.json
- .gitignore
- requirements.txt
- karma.conf.js
- package-lock.json
- package.json
- protractor.conf.js
- README.md
- tsconfig.json
- tslint.json
- bin/
- src/
- node_modules/
- test/
- e2e/